### ISSUE TITLE
How is the cam posing ?

### ISSUE THREAD

**Issue by antiDigest** [kruthikavishwanath/dronedeploy#1]
I don't understand the cam boxes you have in your images ? Could you explain how the cam is posing and how we get to know that by the boxes being shown in your images ?

**Comment by honeybee12P** [comment]
Hi Evamy,

Here the cuboid is imitating the camera. 

Firstly, I get the dimensions of the camera wrt to image1 (bar code image) wherein z =0. Using homography (gives the matrix of transformation match between bar code image & bar code on carpet image) and dimensions wrt to image1, I get the pose of the camera. After using homogrpahy, we get to know the z value and hence pose.
